# Generated by Django 4.2.5 on 2023-10-12 22:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='SassProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposal_name', models.SlugField(max_length=80, unique=True)),
                ('Problem_identification', models.TextField(max_length=1000)),
                ('Research_purpose', models.TextField(max_length=800)),
                ('Project_design', models.TextField(max_length=1000)),
                ('Gender_equality', models.TextField(max_length=500)),
                ('Research_ethics', models.TextField(max_length=500)),
                ('Critical_risks', models.TextField(max_length=500)),
                ('Monitoring_Evaluation', models.TextField(max_length=700)),
                ('Project_Team', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='SonasProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposal_name', models.SlugField(max_length=80, unique=True)),
                ('Personal_statement', models.TextField(max_length=799)),
                ('Research_Proposal', models.TextField(max_length=999)),
                ('Research_environment', models.TextField(max_length=500)),
                ('Research_Team_Capacity', models.TextField(max_length=500)),
                ('IRB_Ethics', models.TextField(max_length=299)),
                ('Additional_funding', models.TextField(max_length=299)),
                ('Project_Timeline', models.TextField(max_length=499)),
                ('Budget', models.TextField(max_length=499)),
                ('NHIF_Biosketch', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(blank=True, max_length=254, null=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='user_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_teach', models.BooleanField(default=False)),
                ('is_student', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
