# Generated by Django 4.2.5 on 2023-10-15 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SassProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposal_name', models.SlugField(max_length=80, unique=True)),
                ('Problem_identification', models.TextField(max_length=1000)),
                ('Research_purpose', models.TextField(max_length=800)),
                ('Project_design', models.TextField(max_length=1000)),
                ('Gender_equality', models.TextField(max_length=500)),
                ('Research_ethics', models.TextField(max_length=500)),
                ('Critical_risks', models.TextField(max_length=500)),
                ('Monitoring_Evaluation', models.TextField(max_length=700)),
                ('Project_Team', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='SonasProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposal_name', models.SlugField(max_length=80, unique=True)),
                ('Personal_statement', models.TextField(max_length=799)),
                ('Research_Proposal', models.TextField(max_length=999)),
                ('Research_environment', models.TextField(max_length=500)),
                ('Research_Team_Capacity', models.TextField(max_length=500)),
                ('IRB_Ethics', models.TextField(max_length=299)),
                ('Additional_funding', models.TextField(max_length=299)),
                ('Project_Timeline', models.TextField(max_length=499)),
                ('Budget', models.TextField(max_length=499)),
                ('NHIF_Biosketch', models.FileField(upload_to='')),
            ],
        ),
    ]
